// Generated by gencpp from file navigation2/enc_feed.msg
// DO NOT EDIT!


#ifndef NAVIGATION2_MESSAGE_ENC_FEED_H
#define NAVIGATION2_MESSAGE_ENC_FEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation2
{
template <class ContainerAllocator>
struct enc_feed_
{
  typedef enc_feed_<ContainerAllocator> Type;

  enc_feed_()
    : vel(0)
    , angle(0)  {
    }
  enc_feed_(const ContainerAllocator& _alloc)
    : vel(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef int16_t _vel_type;
  _vel_type vel;

   typedef int16_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::navigation2::enc_feed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation2::enc_feed_<ContainerAllocator> const> ConstPtr;

}; // struct enc_feed_

typedef ::navigation2::enc_feed_<std::allocator<void> > enc_feed;

typedef boost::shared_ptr< ::navigation2::enc_feed > enc_feedPtr;
typedef boost::shared_ptr< ::navigation2::enc_feed const> enc_feedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation2::enc_feed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation2::enc_feed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation2::enc_feed_<ContainerAllocator1> & lhs, const ::navigation2::enc_feed_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation2::enc_feed_<ContainerAllocator1> & lhs, const ::navigation2::enc_feed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation2::enc_feed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation2::enc_feed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation2::enc_feed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation2::enc_feed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation2::enc_feed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation2::enc_feed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation2::enc_feed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7d324c5346393c6bc385a7a281fa92c";
  }

  static const char* value(const ::navigation2::enc_feed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7d324c5346393c6ULL;
  static const uint64_t static_value2 = 0xbc385a7a281fa92cULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation2::enc_feed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation2/enc_feed";
  }

  static const char* value(const ::navigation2::enc_feed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation2::enc_feed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 vel\n"
"int16 angle\n"
;
  }

  static const char* value(const ::navigation2::enc_feed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation2::enc_feed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enc_feed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation2::enc_feed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation2::enc_feed_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vel);
    s << indent << "angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION2_MESSAGE_ENC_FEED_H
