// Generated by gencpp from file navigation2/Goal.msg
// DO NOT EDIT!


#ifndef NAVIGATION2_MESSAGE_GOAL_H
#define NAVIGATION2_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation2
{
template <class ContainerAllocator>
struct Goal_
{
  typedef Goal_<ContainerAllocator> Type;

  Goal_()
    : bearing(0.0)
    , distance(0.0)  {
    }
  Goal_(const ContainerAllocator& _alloc)
    : bearing(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _bearing_type;
  _bearing_type bearing;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::navigation2::Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation2::Goal_<ContainerAllocator> const> ConstPtr;

}; // struct Goal_

typedef ::navigation2::Goal_<std::allocator<void> > Goal;

typedef boost::shared_ptr< ::navigation2::Goal > GoalPtr;
typedef boost::shared_ptr< ::navigation2::Goal const> GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation2::Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation2::Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation2::Goal_<ContainerAllocator1> & lhs, const ::navigation2::Goal_<ContainerAllocator2> & rhs)
{
  return lhs.bearing == rhs.bearing &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation2::Goal_<ContainerAllocator1> & lhs, const ::navigation2::Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation2::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation2::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation2::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation2::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation2::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation2::Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation2::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6b9899956f1eacd3991a6d711941249";
  }

  static const char* value(const ::navigation2::Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6b9899956f1eacdULL;
  static const uint64_t static_value2 = 0x3991a6d711941249ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation2::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation2/Goal";
  }

  static const char* value(const ::navigation2::Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation2::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 bearing\n"
"float64 distance\n"
;
  }

  static const char* value(const ::navigation2::Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation2::Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bearing);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation2::Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation2::Goal_<ContainerAllocator>& v)
  {
    s << indent << "bearing: ";
    Printer<double>::stream(s, indent + "  ", v.bearing);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION2_MESSAGE_GOAL_H
